//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF2Items.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TF2Items.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exclamation {
            get {
                object obj = ResourceManager.GetObject("exclamation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files|*.*.
        /// </summary>
        internal static string Form1_BtnSaveAsClick_All_files____ {
            get {
                return ResourceManager.GetString("Form1_BtnSaveAsClick_All_files____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///After saving, remember to place this in your \steamapps\username\team fortress 2\tf\scripts\items\ folder!.
        /// </summary>
        internal static string Form1_button1_Click_ {
            get {
                return ResourceManager.GetString("Form1_button1_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted successfully to .
        /// </summary>
        internal static string Form1_button1_Click_Extracted_successfully_to_ {
            get {
                return ResourceManager.GetString("Form1_button1_Click_Extracted_successfully_to_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HLExtract.exe is missing from the program folder!.
        /// </summary>
        internal static string Form1_button1_Click_HLExtract_exe_is_missing_from_the_program_folder_ {
            get {
                return ResourceManager.GetString("Form1_button1_Click_HLExtract_exe_is_missing_from_the_program_folder_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HLLib.dll is missing from the program folder!.
        /// </summary>
        internal static string Form1_button1_Click_HLLib_dll_is_missing_from_the_program_folder_ {
            get {
                return ResourceManager.GetString("Form1_button1_Click_HLLib_dll_is_missing_from_the_program_folder_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items_game.txt|items_game.txt|Team Fortress 2 content|team fortress 2 content.gcf.
        /// </summary>
        internal static string Form1_button1_Click_items_game_txt_items_game_txt_Team_Fortress_2_content_team_fortress_2_content_gcf {
            get {
                return ResourceManager.GetString("Form1_button1_Click_items_game_txt_items_game_txt_Team_Fortress_2_content_team_fo" +
                        "rtress_2_content_gcf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen up!.
        /// </summary>
        internal static string Form1_button1_Click_Listen_up_ {
            get {
                return ResourceManager.GetString("Form1_button1_Click_Listen_up_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an item.
        /// </summary>
        internal static string Form1_button1_Click_Select_an_item {
            get {
                return ResourceManager.GetString("Form1_button1_Click_Select_an_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select items_game.txt or team fortress 2 content.gcf.
        /// </summary>
        internal static string Form1_button1_Click_Select_items_game_txt_or_team_fortress_2_content_gcf {
            get {
                return ResourceManager.GetString("Form1_button1_Click_Select_items_game_txt_or_team_fortress_2_content_gcf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong when extracting :(.
        /// </summary>
        internal static string Form1_button1_Click_Something_went_wrong_when_extracting___ {
            get {
                return ResourceManager.GetString("Form1_button1_Click_Something_went_wrong_when_extracting___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who sent all these babies to fight?!.
        /// </summary>
        internal static string Form1_button1_Click_Who_send_all_these_babies_to_fight__ {
            get {
                return ResourceManager.GetString("Form1_button1_Click_Who_send_all_these_babies_to_fight__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any file|*.*.
        /// </summary>
        internal static string Form1_Button1Click2_Any_file____ {
            get {
                return ResourceManager.GetString("Form1_Button1Click2_Any_file____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file to save the item to.
        /// </summary>
        internal static string Form1_Button1Click2_Select_a_file_to_save_the_item_to {
            get {
                return ResourceManager.GetString("Form1_Button1Click2_Select_a_file_to_save_the_item_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while saving!.
        /// </summary>
        internal static string Form1_SaveFile_Something_went_wrong_while_saving_ {
            get {
                return ResourceManager.GetString("Form1_SaveFile_Something_went_wrong_while_saving_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who sent all these babies to fight!?.
        /// </summary>
        internal static string Form1_SaveFile_Who_send_all_these_babies_to_fight__ {
            get {
                return ResourceManager.GetString("Form1_SaveFile_Who_send_all_these_babies_to_fight__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After saving, remember to place this in your \steamapps\username\team fortress 2\tf\resources\ folder!.
        /// </summary>
        internal static string MainForm_btnEngSave_Click_ {
            get {
                return ResourceManager.GetString("MainForm_btnEngSave_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve saved the file, but hl2.exe (which could be TF2) seems to be open. To see the changes you made, please restart the game. If TF2 isn&apos;t open, ignore this message..
        /// </summary>
        internal static string MainForm_BtnSaveClick_I_ve_saved_the_file__but_TF2_seems_to_be_open__To_see_the_changes_you_made__please_restart_the_game_ {
            get {
                return ResourceManager.GetString("MainForm_BtnSaveClick_I_ve_saved_the_file__but_TF2_seems_to_be_open__To_see_the_c" +
                        "hanges_you_made__please_restart_the_game_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice job, pardner!.
        /// </summary>
        internal static string MainForm_BtnSaveClick_Nice_job__pardner_ {
            get {
                return ResourceManager.GetString("MainForm_BtnSaveClick_Nice_job__pardner_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve reached the maximum number of set items allowed!
        ///It&apos;s just impossible to equip more than .
        /// </summary>
        internal static string MainForm_Button2Click_ {
            get {
                return ResourceManager.GetString("MainForm_Button2Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  items at once!.
        /// </summary>
        internal static string MainForm_Button2Click__items_at_once_ {
            get {
                return ResourceManager.GetString("MainForm_Button2Click__items_at_once_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item already exists in the set!.
        /// </summary>
        internal static string MainForm_Button2Click_This_item_already_exists_in_the_set_ {
            get {
                return ResourceManager.GetString("MainForm_Button2Click_This_item_already_exists_in_the_set_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tf_english.txt or team fortress content.gcf.
        /// </summary>
        internal static string MainForm_EnglishOpenClick_Select_tf_english_txt_or_team_fortress_content_gcf {
            get {
                return ResourceManager.GetString("MainForm_EnglishOpenClick_Select_tf_english_txt_or_team_fortress_content_gcf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tf_english.txt|tf_english.txt|Team Fortress 2 content|team fortress 2 content.gcf.
        /// </summary>
        internal static string MainForm_EnglishOpenClick_tf_english_txt_tf_english_txt_Team_Fortress_2_content_team_fortress_2_content_gcf {
            get {
                return ResourceManager.GetString("MainForm_EnglishOpenClick_tf_english_txt_tf_english_txt_Team_Fortress_2_content_t" +
                        "eam_fortress_2_content_gcf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF2 Items Editor v.
        /// </summary>
        internal static string MainForm_MainFormLoad_TF2_Items_Editor_v {
            get {
                return ResourceManager.GetString("MainForm_MainFormLoad_TF2_Items_Editor_v", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tf2itemsmanager {
            get {
                object obj = ResourceManager.GetObject("tf2itemsmanager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
